### ISSUE TITLE
Show Page CSS

### ISSUE THREAD

**Issue by HunterNyan** [HiveMedia/TheHiveRadio#11]
Well the entire style is a mess.

**Comment by KatelynHaworth** [comment]
Is the code up to date in develop for me to style?

**Comment by HunterNyan** [comment]
Yep. I've pushed everything up for you

**Comment by KatelynHaworth** [comment]
This is a priority so I shall work on this one first, will branch off into bugfix/11-show-page-css

**Comment by KatelynHaworth** [comment]
Done as much as I can tonight @HunterNyan, I will do what I can before, during and after work, otherwise it is going to be a long night tomorrow night of power coding

**Comment by KatelynHaworth** [comment]
Been fixed along side the implementation of #9, awaiting merge into develop

**Comment by KatelynHaworth** [comment]
Merged into develop
