### ISSUE TITLE
Blog aka /b

### ISSUE THREAD

**Issue by HunterNyan** [HiveMedia/TheHiveRadio#25]
The text of blog and posts is wrong, you'll understand as soon as you see it

**Comment by KatelynHaworth** [comment]
On it! Will attempt to get this out of the way as quick as possible

**Comment by KatelynHaworth** [comment]
Everything has been cleaned up, it is a bit messy behind the scenes but on the front side it looks and acts how it should. The controller code really needs to be cleaned up but that can be done in release 0.2 or 0.3

**Comment by KatelynHaworth** [comment]
Work was done in bugfix/#25-fix-blog-styling

**Comment by KatelynHaworth** [comment]
Fixed and closed
