### ISSUE TITLE
Icecast module returning mucked up listener values

### ISSUE THREAD

**Issue by KatelynHaworth** [HiveMedia/TheHiveRadio#30]
Having a look at the API I noticed something strange and not right going on:

```
{
    status: "successful",
    result: {
        server_version: "Icecast 2.3.3",
        server_admin: "production@hiveradio.net",
        server_location: null,
        server_listeners_total: 5,
        server_listeners_unique: 6,
        server_listeners_peak: 15,
        server_listeners_max: -1,
        server_streams: [ ... ] // Been redacted to keep the message short
    },
    timestamp: 1426463209
}
```

The problem here is that `server_listeners_total` is reporting less than `server_listeners_unique`, this is not logical and is causing partner system to be the wrong stats about listeners on the station and give us back invalid statistics.

**Comment by KatelynHaworth** [comment]
@HunterNyan, when NGINX is reverse proxying, does it pass on the requesters IP or does it only get the local loop back address?

**Comment by HunterNyan** [comment]
well sort yes and no, it'll use X-Forwarded for headers. I doubt Icecast can support this which will be nesseciary for us

**Comment by HunterNyan** [comment]
http://karlheyes.github.io/
So umm Next Major Release will support X-Forwarded addresses, Or we switch branches.

We should also look into suing PHP for Authing DJs to the Stream

**Comment by HunterNyan** [comment]
Fixed
