### ISSUE TITLE
HALP

### ISSUE THREAD

**Issue by HunterNyan** [HiveMedia/TheHiveRadio#34]
Can you figure out why listshoweps of ShowAdminContorller returns false?

**Comment by KatelynHaworth** [comment]
@HunterNyan what branch?

**Comment by KatelynHaworth** [comment]
nvm, found it in `develop`, got any corpus data?

**Comment by HunterNyan** [comment]
No, you'll need to:
1) Apply for a Show
2) Approve it
3) Upload Ep

**Comment by HunterNyan** [comment]
Fixed
