### ISSUE TITLE
Web Player

### ISSUE THREAD

**Issue by HunterNyan** [HiveMedia/TheHiveRadio#9]
We need to shove the floating web player in the Header

**Comment by HunterNyan** [comment]
I'll be playing aorund with this in a branch web-player

**Comment by KatelynHaworth** [comment]
Remember that when making commit for a issue to put the issue number at the start of the commit, e.g. "#9 - Some commit that fixes or adds something"

**Comment by HunterNyan** [comment]
Is it # or @ for github

**Comment by KatelynHaworth** [comment]
This and #11 have been fixed/implemented and may be closed off after being pulled into develop

**Comment by KatelynHaworth** [comment]
Merged into develop
